<?php
// $Id$

/**
 * @file
 * Provides a public API to access budget data.
 *
 * Implements the City Budget data schema with a web service.
 */

/**
* Implementation of hook_menu().
*/
function citybudget_menu() {
  $items['budget'] = array(
    'title' => 'Budget',
    'page callback' => 'citybudget_function',
    'access arguments' => array('access city budget data'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'annotate.admin.inc',
  );
  return $items;
}

/**
* Implementation of hook_perm().
*/
function citybudget_perm() {
  return array(
    'administer city budget',
    'access city budget data',
  );
}

function citybudget_function() {
  return 'asdf';
}