<?php
// $Id$

/**
 * @file
 * Provides a public API to access budget data.
 *
 * Implements the City Budget data schema with a web service.
 */

define('CITYBUDGET_CATEGORY_EXPENSE', 0);
define('CITYBUDGET_CATEGORY_REVENUE', 1);
define('CITYBUDGET_CATEGORY_BOTH', 2);

/**
* Implementation of hook_menu().
*/
function citybudget_menu() {
  $items['budget'] = array(
    'title' => 'Budget',
    'page callback' => 'citybudget_function',
    'access arguments' => array('access city budget data'),
  );
  $items['admin/content/citybudget'] = array(
    'title' => 'Import Budget Data',
    'description' => 'Import new budget data from CSV.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('citybudget_import_data'),
    'access arguments' => array('administer city budget'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'citybudget.admin.inc',
  );
  return $items;
}

/**
* Implementation of hook_perm().
*/
function citybudget_perm() {
  return array(
    'administer city budget',
    'access city budget data',
  );
}

function citybudget_function() {
  return 'asdf';
}

function _citybudget_get_budget_program($program_name) {
  $is_program_exist = false;
  $programs = _citybudget_list_programs('programs');
  foreach($programs as $program_id => $program) {
    if($program_name == $program->name) {
      $is_program_exist = true;
      break;
    }
  }
  
  if($is_program_exist) {
    $query = 'SELECT * FROM {citybudget_line_items} WHERE program_id = %d';
    $results = db_query($query, array($program_id));
    
    $categories = _citybudget_list_categories();
    $line_items = array();
    while($result = db_fetch_object($results)) {
      $category_id = $result->category_id;
      unset($result->program_id);
      unset($result->category_id);
      $line_items[$categories[$category_id]->name] = $result;
    }
    $program->line_items = $line_items;
    return $program;
  } else {
    return FALSE;
  }
}

function _citybudget_list_entity_names($entity_type = 'programs') {
  $entity_types = array('clusters', 'programs', 'categories');
  
  if(!in_array($entity_type, $entity_types)) {
    return FALSE;
  }
  
  $query = 'SELECT * FROM {citybudget_' . $entity_type . '}';
  $results = db_query($query);
  
  $entities = array();
  while($result = db_fetch_object($results)) {
    $entities[] = $result->name;
  }
  return $entities;
}

function _citybudget_list_clusters() {
  $query = 'SELECT * FROM {citybudget_clusters}';
  $results = db_query($query);
  
  $clusters = array();
  while($result = db_fetch_object($results)) {
    $result_id = $result->id;
    unset($result->id);
    $clusters[$result_id] = $result;
  }
  return $clusters;
}

function _citybudget_list_programs($programs = array()) {
  $query = 'SELECT * FROM {citybudget_programs}';
  
  $results = db_query($query);
  
  $clusters = _citybudget_list_clusters();
  $programs = array();
  while($result = db_fetch_object($results)) {
    $result_id = $result->id;
    $result->cluster_name = $clusters[$result->cluster_id]->name;
    unset($result->cluster_id);
    unset($result->id);
    $programs[$result_id] = $result;
  }
  return $programs;
}

function _citybudget_list_categories() {
  $query = 'SELECT * FROM {citybudget_categories}';
  $results = db_query($query);
  
  $categories = array();
  while($result = db_fetch_object($results)) {
    $result_id = $result->id;
    unset($result->id);
    
    switch($result->type) {
      case CITYBUDGET_CATEGORY_EXPENSE:
        $result->type = 'expense';
        break;
      case CITYBUDGET_CATEGORY_REVENUE:
        $result->type = 'revenue';
        break;
    }
    
    $categories[$result_id] = $result;
  }
  return $categories;
}
